### ISSUE TITLE
运行flash_attn带来的错误

### ISSUE THREAD

**Issue by lonngxiang** [zhangfaen/finetune-Qwen2-VL#2] opened 2024-09-11 07:01 UTC
out, q, k, v, out_padded, softmax_lse, S_dmask, rng_state = flash_attn_cuda.fwd(
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [298,0,0], thread: [64,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [298,0,0], thread: [65,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.

**Comment by lonngxiang** [comment] 2024-09-11 07:01
flash-attn                        2.6.3

**Comment by lonngxiang** [comment] 2024-09-11 07:02
![image](https://github.com/user-attachments/assets/d56342b6-f69e-41c0-bdd1-85e225c04a4e)

**Comment by zhangfaen** [comment] 2024-09-12 09:51
I debugged what is wrong when enable flash_attention_2 in finetune.py. 

Conclusion: fixed, see my latest commit https://github.com/zhangfaen/finetune-Qwen2-VL/commit/ff383f7b03b3beb5e8c5ca83c1ddc004ca7a2eec

How:
1. the root cause was from a bug of src/transformers/models/qwen2_vl/modeling_qwen2_vl.py 
2. qwen team fixed that bug, see  https://github.com/huggingface/transformers/commit/21fac7abba2a37fae86106f87fcf9974fd1e3830

Solution:
1. get latest of this repo by "git pull https://github.com/zhangfaen/finetune-Qwen2-VL/"
2. pip uninstall transformers
3. pip install -r requirements.txt

**Comment by zhangfaen** [comment] 2024-09-12 09:52
I closed this issue. 
if you still have problem, feel free to re-open it.

**Closed by zhangfaen** 2024-09-12 09:52 UTC

**Comment by lonngxiang** [comment] 2024-09-12 10:55
收到，可以训练了，就是显存占用还是不低；好项目，用pytorch原生训练

**Comment by Guangming92** [comment] 2024-09-14 03:39
@lonngxiang 麻烦问下，用的什么显卡？我用的4090，24G显存，迭代一轮就报显存不足~你数据量多大？可否交流一下？

**Comment by lonngxiang** [comment] 2024-09-14 03:45
重新安装新transformers后，可以训练，也是4090，就是加载很慢

**Comment by Guangming92** [comment] 2024-09-14 06:15
> 重新安装新transformers后，可以训练，也是4090，就是加载很慢
我按照上面指导，重新按照requirements.txt安装的库，之前确实也报跟你之前一样的问题，重新安装了，不报找不到索引的问题，但是提示显存不足，程序退出，训练数据都是按照demo来的，并且在加载模型的时候添加参数torch_dtype=torch.bfloat16, attn_implementation='flash_attention_2'
![image](https://github.com/user-attachments/assets/f872494d-e47e-4c26-b10f-61765ce57c4e)
请教一下，你执行的时候调整了哪些内容？基础模型是Qwen2-VL-2B-Instruct吗？

**Comment by lonngxiang** [comment] 2024-09-14 13:25
是，就把batch调成1了，
![2eda960972ff493d692abec4d50faa06_c883dc392317403c8e35d5502fd1f0b3](https://github.com/user-attachments/assets/9c569da2-cc8a-421f-8aa1-0efbcc32230e)

**Comment by 476258834lzx** [comment] 2024-09-18 10:21
> ![image](https://private-user-images.githubusercontent.com/40717349/366335086-d56342b6-f69e-41c0-bdd1-85e225c04a4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NTUxNTAsIm5iZiI6MTcyNjY1NDg1MCwicGF0aCI6Ii80MDcxNzM0OS8zNjYzMzUwODYtZDU2MzQyYjYtZjY5ZS00MWMwLWJkZDEtODVlMjI1YzA0YTRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDEwMjA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliY2JjYTU2M2E3ZjA2NDBlNjAwY2E2NjMwMTRlZjkwMTJlMTFjZWU4NmYzMTFjNjNlMmEwMWQ5ODkxMGFiZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rsbD4T07mhEfzzXSbkykXPrabBn6lqg1TPDgmtAHzT4)

你好 ，请问 你是怎么解决的

**Comment by 476258834lzx** [comment] 2024-09-18 10:22
> > 重新安装新transformers后，可以训练，也是4090，就是加载很慢
> > 我按照上面指导，重新按照requirements.txt安装的库，之前确实也报跟你之前一样的问题，重新安装了，不报找不到索引的问题，但是提示显存不足，程序退出，训练数据都是按照demo来的，并且在加载模型的时候添加参数torch_dtype=torch.bfloat16, attn_implementation='flash_attention_2'
> > ![image](https://private-user-images.githubusercontent.com/57172408/367492993-f872494d-e47e-4c26-b10f-61765ce57c4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NTUxNTAsIm5iZiI6MTcyNjY1NDg1MCwicGF0aCI6Ii81NzE3MjQwOC8zNjc0OTI5OTMtZjg3MjQ5NGQtZTQ3ZS00YzI2LWIxMGYtNjE3NjVjZTU3YzRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDEwMjA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNGE4MDNlNjg0ZTkwNDJmZWFjMTFjN2U0OTEwZGQ5ZTg4Njg0MjZjYzY5OTZhZDZmMjVhYWVlOGY2MjBhZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aWpo9IrPKiAyQIKGBDKMmwZ_i8WXmh13OrMJNmmz0tk)
> > 请教一下，你执行的时候调整了哪些内容？基础模型是Qwen2-VL-2B-Instruct吗？

你好，请问，你跑起来了吗
